import type { RealisationPhoto } from "@/content/types";

/**
 * Manifest des photos de chantier (galerie /realisations).
 * Généré par scripts/import-legacy-images.mjs à partir des photos réelles de
 * l'ancien site (dédoublonnées MD5, renommées SEO). Dimensions réelles relevées.
 */
export const realisationsPhotos: readonly RealisationPhoto[] = [
  {
    src: "/images/realisations/chantier-couverture-loiret-01.jpeg",
    alt: "Chantier de rénovation de toiture réalisé par JCD Rénovation dans le Loiret — photo 1",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-02.jpeg",
    alt: "Pose de tuiles sur une toiture par les couvreurs JCD Rénovation — photo 2",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-03.jpeg",
    alt: "Travaux de couverture en cours sur un chantier JCD Rénovation près de Villemandeur — photo 3",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-04.jpeg",
    alt: "Toiture en cours de rénovation par JCD Rénovation, couvreur dans le Loiret — photo 4",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-05.jpeg",
    alt: "Chantier de couverture avec échafaudage sécurisé — JCD Rénovation — photo 5",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-06.jpeg",
    alt: "Réfection de toiture par l'équipe JCD Rénovation dans l'agglomération Montargoise — photo 6",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-07.jpeg",
    alt: "Chantier de rénovation de toiture réalisé par JCD Rénovation dans le Loiret — photo 7",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-08.jpeg",
    alt: "Pose de tuiles sur une toiture par les couvreurs JCD Rénovation — photo 8",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-09.jpeg",
    alt: "Travaux de couverture en cours sur un chantier JCD Rénovation près de Villemandeur — photo 9",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-10.jpeg",
    alt: "Toiture en cours de rénovation par JCD Rénovation, couvreur dans le Loiret — photo 10",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-11.jpeg",
    alt: "Chantier de couverture avec échafaudage sécurisé — JCD Rénovation — photo 11",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-12.jpeg",
    alt: "Réfection de toiture par l'équipe JCD Rénovation dans l'agglomération Montargoise — photo 12",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-13.jpeg",
    alt: "Chantier de rénovation de toiture réalisé par JCD Rénovation dans le Loiret — photo 13",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-14.jpeg",
    alt: "Pose de tuiles sur une toiture par les couvreurs JCD Rénovation — photo 14",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-15.jpeg",
    alt: "Travaux de couverture en cours sur un chantier JCD Rénovation près de Villemandeur — photo 15",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-16.jpeg",
    alt: "Toiture en cours de rénovation par JCD Rénovation, couvreur dans le Loiret — photo 16",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-17.jpeg",
    alt: "Chantier de couverture avec échafaudage sécurisé — JCD Rénovation — photo 17",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-18.jpeg",
    alt: "Réfection de toiture par l'équipe JCD Rénovation dans l'agglomération Montargoise — photo 18",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-19.jpeg",
    alt: "Chantier de rénovation de toiture réalisé par JCD Rénovation dans le Loiret — photo 19",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-20.jpeg",
    alt: "Pose de tuiles sur une toiture par les couvreurs JCD Rénovation — photo 20",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-21.jpeg",
    alt: "Travaux de couverture en cours sur un chantier JCD Rénovation près de Villemandeur — photo 21",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-22.jpeg",
    alt: "Toiture en cours de rénovation par JCD Rénovation, couvreur dans le Loiret — photo 22",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-23.jpeg",
    alt: "Chantier de couverture avec échafaudage sécurisé — JCD Rénovation — photo 23",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-24.jpeg",
    alt: "Réfection de toiture par l'équipe JCD Rénovation dans l'agglomération Montargoise — photo 24",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-25.jpeg",
    alt: "Chantier de rénovation de toiture réalisé par JCD Rénovation dans le Loiret — photo 25",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-26.jpeg",
    alt: "Pose de tuiles sur une toiture par les couvreurs JCD Rénovation — photo 26",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-27.jpeg",
    alt: "Travaux de couverture en cours sur un chantier JCD Rénovation près de Villemandeur — photo 27",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-28.jpeg",
    alt: "Toiture en cours de rénovation par JCD Rénovation, couvreur dans le Loiret — photo 28",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-29.jpeg",
    alt: "Chantier de couverture avec échafaudage sécurisé — JCD Rénovation — photo 29",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-30.jpeg",
    alt: "Réfection de toiture par l'équipe JCD Rénovation dans l'agglomération Montargoise — photo 30",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-31.jpeg",
    alt: "Chantier de rénovation de toiture réalisé par JCD Rénovation dans le Loiret — photo 31",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-32.jpeg",
    alt: "Pose de tuiles sur une toiture par les couvreurs JCD Rénovation — photo 32",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-33.jpeg",
    alt: "Travaux de couverture en cours sur un chantier JCD Rénovation près de Villemandeur — photo 33",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-34.jpeg",
    alt: "Toiture en cours de rénovation par JCD Rénovation, couvreur dans le Loiret — photo 34",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-35.jpeg",
    alt: "Chantier de couverture avec échafaudage sécurisé — JCD Rénovation — photo 35",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-36.jpeg",
    alt: "Réfection de toiture par l'équipe JCD Rénovation dans l'agglomération Montargoise — photo 36",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-37.jpeg",
    alt: "Chantier de rénovation de toiture réalisé par JCD Rénovation dans le Loiret — photo 37",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-38.jpeg",
    alt: "Pose de tuiles sur une toiture par les couvreurs JCD Rénovation — photo 38",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-39.jpeg",
    alt: "Travaux de couverture en cours sur un chantier JCD Rénovation près de Villemandeur — photo 39",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-40.jpeg",
    alt: "Toiture en cours de rénovation par JCD Rénovation, couvreur dans le Loiret — photo 40",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-41.jpeg",
    alt: "Chantier de couverture avec échafaudage sécurisé — JCD Rénovation — photo 41",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-42.jpeg",
    alt: "Réfection de toiture par l'équipe JCD Rénovation dans l'agglomération Montargoise — photo 42",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-43.jpeg",
    alt: "Chantier de rénovation de toiture réalisé par JCD Rénovation dans le Loiret — photo 43",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-44.jpeg",
    alt: "Pose de tuiles sur une toiture par les couvreurs JCD Rénovation — photo 44",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-45.jpeg",
    alt: "Travaux de couverture en cours sur un chantier JCD Rénovation près de Villemandeur — photo 45",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-46.jpeg",
    alt: "Toiture en cours de rénovation par JCD Rénovation, couvreur dans le Loiret — photo 46",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-47.jpeg",
    alt: "Chantier de couverture avec échafaudage sécurisé — JCD Rénovation — photo 47",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-48.jpeg",
    alt: "Réfection de toiture par l'équipe JCD Rénovation dans l'agglomération Montargoise — photo 48",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-49.jpeg",
    alt: "Chantier de rénovation de toiture réalisé par JCD Rénovation dans le Loiret — photo 49",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-50.jpeg",
    alt: "Pose de tuiles sur une toiture par les couvreurs JCD Rénovation — photo 50",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-51.jpeg",
    alt: "Travaux de couverture en cours sur un chantier JCD Rénovation près de Villemandeur — photo 51",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-52.jpeg",
    alt: "Toiture en cours de rénovation par JCD Rénovation, couvreur dans le Loiret — photo 52",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-53.jpeg",
    alt: "Chantier de couverture avec échafaudage sécurisé — JCD Rénovation — photo 53",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-54.jpeg",
    alt: "Réfection de toiture par l'équipe JCD Rénovation dans l'agglomération Montargoise — photo 54",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-55.jpeg",
    alt: "Chantier de rénovation de toiture réalisé par JCD Rénovation dans le Loiret — photo 55",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-56.jpeg",
    alt: "Pose de tuiles sur une toiture par les couvreurs JCD Rénovation — photo 56",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-57.jpeg",
    alt: "Travaux de couverture en cours sur un chantier JCD Rénovation près de Villemandeur — photo 57",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-58.jpeg",
    alt: "Toiture en cours de rénovation par JCD Rénovation, couvreur dans le Loiret — photo 58",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-59.jpeg",
    alt: "Chantier de couverture avec échafaudage sécurisé — JCD Rénovation — photo 59",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-60.jpeg",
    alt: "Réfection de toiture par l'équipe JCD Rénovation dans l'agglomération Montargoise — photo 60",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-61.jpeg",
    alt: "Chantier de rénovation de toiture réalisé par JCD Rénovation dans le Loiret — photo 61",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-62.jpeg",
    alt: "Pose de tuiles sur une toiture par les couvreurs JCD Rénovation — photo 62",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-63.jpeg",
    alt: "Travaux de couverture en cours sur un chantier JCD Rénovation près de Villemandeur — photo 63",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-64.jpeg",
    alt: "Toiture en cours de rénovation par JCD Rénovation, couvreur dans le Loiret — photo 64",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-65.jpeg",
    alt: "Chantier de couverture avec échafaudage sécurisé — JCD Rénovation — photo 65",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-66.jpeg",
    alt: "Réfection de toiture par l'équipe JCD Rénovation dans l'agglomération Montargoise — photo 66",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-67.jpeg",
    alt: "Chantier de rénovation de toiture réalisé par JCD Rénovation dans le Loiret — photo 67",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-68.jpeg",
    alt: "Pose de tuiles sur une toiture par les couvreurs JCD Rénovation — photo 68",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-69.jpeg",
    alt: "Travaux de couverture en cours sur un chantier JCD Rénovation près de Villemandeur — photo 69",
    width: 1200,
    height: 1600,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-70.jpeg",
    alt: "Toiture en cours de rénovation par JCD Rénovation, couvreur dans le Loiret — photo 70",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
  {
    src: "/images/realisations/chantier-couverture-loiret-71.jpeg",
    alt: "Chantier de couverture avec échafaudage sécurisé — JCD Rénovation — photo 71",
    width: 1600,
    height: 1200,
    category: "couverture",
  },
] as const;
